# fly.toml app configuration file generated for likelion-cicd-kangdaeun1022 on 2026-09-23T23:29:28+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'likelion-cicd-kangdaeun1022'
primary_region = 'nrt'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
